/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  S3ConfigRequest,
  S3ConfigResponse,
  S3SuccessResponse,
  S3TestResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    S3ConfigRequestFromJSON,
    S3ConfigRequestToJSON,
    S3ConfigResponseFromJSON,
    S3ConfigResponseToJSON,
    S3SuccessResponseFromJSON,
    S3SuccessResponseToJSON,
    S3TestResponseFromJSON,
    S3TestResponseToJSON,
} from '../models/index';

export interface SaveS3ConfigRequest {
    s3ConfigRequest: S3ConfigRequest;
}

/**
 * IntegrationsApi - interface
 * 
 * @export
 * @interface IntegrationsApiInterface
 */
export interface IntegrationsApiInterface {
    /**
     * Delete S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You\'ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary Delete S3 configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    deleteS3ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3SuccessResponse>>;

    /**
     * Delete S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You\'ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Delete S3 configuration
     */
    deleteS3Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3SuccessResponse>;

    /**
     * Get current S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary Get S3 configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    getS3ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3ConfigResponse>>;

    /**
     * Get current S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get S3 configuration
     */
    getS3Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3ConfigResponse>;

    /**
     * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: `secret_access_key` is required - For updates: Omit `secret_access_key` to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary Save S3 configuration
     * @param {S3ConfigRequest} s3ConfigRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    saveS3ConfigRaw(requestParameters: SaveS3ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3SuccessResponse>>;

    /**
     * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: `secret_access_key` is required - For updates: Omit `secret_access_key` to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Save S3 configuration
     */
    saveS3Config(s3ConfigRequest: S3ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3SuccessResponse>;

    /**
     * Test S3 connection with stored credentials.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using `POST /v1/integrations/s3`  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary Test S3 connection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsApiInterface
     */
    testS3ConnectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3TestResponse>>;

    /**
     * Test S3 connection with stored credentials.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using `POST /v1/integrations/s3`  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Test S3 connection
     */
    testS3Connection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3TestResponse>;

}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI implements IntegrationsApiInterface {

    /**
     * Delete S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You\'ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Delete S3 configuration
     */
    async deleteS3ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3SuccessResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/integrations/s3`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => S3SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Remove your S3 integration. Generated PDFs will use the default CDN storage after deletion.  **Warning:** This action is irreversible. You\'ll need to reconfigure S3 to use it again.  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Delete S3 configuration
     */
    async deleteS3Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3SuccessResponse> {
        const response = await this.deleteS3ConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get S3 configuration
     */
    async getS3ConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3ConfigResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/integrations/s3`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => S3ConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get current S3 storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Retrieve your S3 integration settings. Secret access key is masked for security.  **Returns 404** if S3 is not configured.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get S3 configuration
     */
    async getS3Config(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3ConfigResponse> {
        const response = await this.getS3ConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: `secret_access_key` is required - For updates: Omit `secret_access_key` to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Save S3 configuration
     */
    async saveS3ConfigRaw(requestParameters: SaveS3ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3SuccessResponse>> {
        if (requestParameters['s3ConfigRequest'] == null) {
            throw new runtime.RequiredError(
                's3ConfigRequest',
                'Required parameter "s3ConfigRequest" was null or undefined when calling saveS3Config().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/integrations/s3`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: S3ConfigRequestToJSON(requestParameters['s3ConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => S3SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Save or update S3-compatible storage configuration.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Configure your S3-compatible storage to receive generated PDFs directly in your own bucket instead of the default CDN.  **Supported providers:** - Amazon S3 - DigitalOcean Spaces - Cloudflare R2 - MinIO - Any S3-compatible storage  **Secret key behavior:** - For new configuration: `secret_access_key` is required - For updates: Omit `secret_access_key` to keep existing value  **No credits consumed:** This is a configuration endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Save S3 configuration
     */
    async saveS3Config(s3ConfigRequest: S3ConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3SuccessResponse> {
        const response = await this.saveS3ConfigRaw({ s3ConfigRequest: s3ConfigRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Test S3 connection with stored credentials.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using `POST /v1/integrations/s3`  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Test S3 connection
     */
    async testS3ConnectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<S3TestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/integrations/s3/test`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => S3TestResponseFromJSON(jsonValue));
    }

    /**
     * Test S3 connection with stored credentials.  **Authentication:** API Key required (`x-api-key` header)  **Usage:** Verify your S3 configuration is working correctly. The test will: 1. Connect to the endpoint 2. Verify bucket access 3. Check write permissions by uploading a small test file  **Prerequisite:** S3 must be configured first using `POST /v1/integrations/s3`  **No credits consumed:** This is a diagnostic endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Test S3 connection
     */
    async testS3Connection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<S3TestResponse> {
        const response = await this.testS3ConnectionRaw(initOverrides);
        return await response.value();
    }

}
