/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAsyncPdfRequest,
  CreateAsyncPdfResponse,
  HTTPValidationError,
  JobListResponse,
  JobStatus,
  JobStatusResponse,
} from '../models/index';
import {
    CreateAsyncPdfRequestFromJSON,
    CreateAsyncPdfRequestToJSON,
    CreateAsyncPdfResponseFromJSON,
    CreateAsyncPdfResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    JobListResponseFromJSON,
    JobListResponseToJSON,
    JobStatusFromJSON,
    JobStatusToJSON,
    JobStatusResponseFromJSON,
    JobStatusResponseToJSON,
} from '../models/index';

export interface CreatePdfAsyncRequest {
    createAsyncPdfRequest: CreateAsyncPdfRequest;
}

export interface GetPdfJobRequest {
    jobId: string;
}

export interface ListPdfJobsRequest {
    limit?: number;
    offset?: number;
    status?: JobStatus | null;
}

/**
 * PDFAsyncApi - interface
 * 
 * @export
 * @interface PDFAsyncApiInterface
 */
export interface PDFAsyncApiInterface {
    /**
     * Queue a PDF generation job for async processing.  **Authentication:** API Key required (`x-api-key` header)  ## How It Works  1. Submit a job with template and data 2. Receive a `job_id` immediately 3. Poll `/v1/pdf/status/{job_id}` for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can\'t wait for synchronous response - You want webhook notifications  ## Webhooks  If `webhook_url` is provided, we\'ll POST to it when the job completes or fails:  ```json {     \"event\": \"pdf.completed\",     \"job_id\": \"...\",     \"status\": \"completed\",     \"result\": {         \"url\": \"https://...\",         \"filename\": \"invoice.pdf\"     } } ```  Webhooks include HMAC-SHA256 signature in `X-TemplateFox-Signature` header if you provide a `webhook_secret`.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
     * @summary Generate PDF asynchronously
     * @param {CreateAsyncPdfRequest} createAsyncPdfRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFAsyncApiInterface
     */
    createPdfAsyncRaw(requestParameters: CreatePdfAsyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAsyncPdfResponse>>;

    /**
     * Queue a PDF generation job for async processing.  **Authentication:** API Key required (`x-api-key` header)  ## How It Works  1. Submit a job with template and data 2. Receive a `job_id` immediately 3. Poll `/v1/pdf/status/{job_id}` for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can\'t wait for synchronous response - You want webhook notifications  ## Webhooks  If `webhook_url` is provided, we\'ll POST to it when the job completes or fails:  ```json {     \"event\": \"pdf.completed\",     \"job_id\": \"...\",     \"status\": \"completed\",     \"result\": {         \"url\": \"https://...\",         \"filename\": \"invoice.pdf\"     } } ```  Webhooks include HMAC-SHA256 signature in `X-TemplateFox-Signature` header if you provide a `webhook_secret`.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
     * Generate PDF asynchronously
     */
    createPdfAsync(createAsyncPdfRequest: CreateAsyncPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAsyncPdfResponse>;

    /**
     * Get the current status of an async PDF generation job.  **Authentication:** API Key required (`x-api-key` header)  ## Status Values  | Status | Description | |--------|-------------| | `pending` | Job is queued, waiting to be processed | | `processing` | Job is being processed | | `completed` | PDF generated successfully | | `failed` | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
     * @summary Get PDF job status
     * @param {string} jobId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFAsyncApiInterface
     */
    getPdfJobRaw(requestParameters: GetPdfJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobStatusResponse>>;

    /**
     * Get the current status of an async PDF generation job.  **Authentication:** API Key required (`x-api-key` header)  ## Status Values  | Status | Description | |--------|-------------| | `pending` | Job is queued, waiting to be processed | | `processing` | Job is being processed | | `completed` | PDF generated successfully | | `failed` | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
     * Get PDF job status
     */
    getPdfJob(jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobStatusResponse>;

    /**
     * List async PDF generation jobs for your team.  **Authentication:** API Key required (`x-api-key` header)  Supports pagination and filtering by status.
     * @summary List PDF jobs
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {JobStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFAsyncApiInterface
     */
    listPdfJobsRaw(requestParameters: ListPdfJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobListResponse>>;

    /**
     * List async PDF generation jobs for your team.  **Authentication:** API Key required (`x-api-key` header)  Supports pagination and filtering by status.
     * List PDF jobs
     */
    listPdfJobs(limit?: number, offset?: number, status?: JobStatus | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobListResponse>;

}

/**
 * 
 */
export class PDFAsyncApi extends runtime.BaseAPI implements PDFAsyncApiInterface {

    /**
     * Queue a PDF generation job for async processing.  **Authentication:** API Key required (`x-api-key` header)  ## How It Works  1. Submit a job with template and data 2. Receive a `job_id` immediately 3. Poll `/v1/pdf/status/{job_id}` for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can\'t wait for synchronous response - You want webhook notifications  ## Webhooks  If `webhook_url` is provided, we\'ll POST to it when the job completes or fails:  ```json {     \"event\": \"pdf.completed\",     \"job_id\": \"...\",     \"status\": \"completed\",     \"result\": {         \"url\": \"https://...\",         \"filename\": \"invoice.pdf\"     } } ```  Webhooks include HMAC-SHA256 signature in `X-TemplateFox-Signature` header if you provide a `webhook_secret`.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
     * Generate PDF asynchronously
     */
    async createPdfAsyncRaw(requestParameters: CreatePdfAsyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAsyncPdfResponse>> {
        if (requestParameters['createAsyncPdfRequest'] == null) {
            throw new runtime.RequiredError(
                'createAsyncPdfRequest',
                'Required parameter "createAsyncPdfRequest" was null or undefined when calling createPdfAsync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf/create-async`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAsyncPdfRequestToJSON(requestParameters['createAsyncPdfRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAsyncPdfResponseFromJSON(jsonValue));
    }

    /**
     * Queue a PDF generation job for async processing.  **Authentication:** API Key required (`x-api-key` header)  ## How It Works  1. Submit a job with template and data 2. Receive a `job_id` immediately 3. Poll `/v1/pdf/status/{job_id}` for completion 4. Optionally receive a webhook notification  ## When to Use Async  Use async generation when: - Processing large documents or batches - You can\'t wait for synchronous response - You want webhook notifications  ## Webhooks  If `webhook_url` is provided, we\'ll POST to it when the job completes or fails:  ```json {     \"event\": \"pdf.completed\",     \"job_id\": \"...\",     \"status\": \"completed\",     \"result\": {         \"url\": \"https://...\",         \"filename\": \"invoice.pdf\"     } } ```  Webhooks include HMAC-SHA256 signature in `X-TemplateFox-Signature` header if you provide a `webhook_secret`.  **Credits:** 1 credit deducted immediately (refunded if job fails permanently).
     * Generate PDF asynchronously
     */
    async createPdfAsync(createAsyncPdfRequest: CreateAsyncPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAsyncPdfResponse> {
        const response = await this.createPdfAsyncRaw({ createAsyncPdfRequest: createAsyncPdfRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Get the current status of an async PDF generation job.  **Authentication:** API Key required (`x-api-key` header)  ## Status Values  | Status | Description | |--------|-------------| | `pending` | Job is queued, waiting to be processed | | `processing` | Job is being processed | | `completed` | PDF generated successfully | | `failed` | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
     * Get PDF job status
     */
    async getPdfJobRaw(requestParameters: GetPdfJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobStatusResponse>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getPdfJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get the current status of an async PDF generation job.  **Authentication:** API Key required (`x-api-key` header)  ## Status Values  | Status | Description | |--------|-------------| | `pending` | Job is queued, waiting to be processed | | `processing` | Job is being processed | | `completed` | PDF generated successfully | | `failed` | Job failed (check error_message) |  ## Polling Recommendations  - Poll every 1-2 seconds for small documents - Poll every 5-10 seconds for large documents - Consider using webhooks instead of polling
     * Get PDF job status
     */
    async getPdfJob(jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobStatusResponse> {
        const response = await this.getPdfJobRaw({ jobId: jobId }, initOverrides);
        return await response.value();
    }

    /**
     * List async PDF generation jobs for your team.  **Authentication:** API Key required (`x-api-key` header)  Supports pagination and filtering by status.
     * List PDF jobs
     */
    async listPdfJobsRaw(requestParameters: ListPdfJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf/jobs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobListResponseFromJSON(jsonValue));
    }

    /**
     * List async PDF generation jobs for your team.  **Authentication:** API Key required (`x-api-key` header)  Supports pagination and filtering by status.
     * List PDF jobs
     */
    async listPdfJobs(limit?: number, offset?: number, status?: JobStatus | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobListResponse> {
        const response = await this.listPdfJobsRaw({ limit: limit, offset: offset, status: status }, initOverrides);
        return await response.value();
    }

}
