/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePdfRequest,
  CreatePdfResponse,
  HTTPValidationError,
} from '../models/index';
import {
    CreatePdfRequestFromJSON,
    CreatePdfRequestToJSON,
    CreatePdfResponseFromJSON,
    CreatePdfResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreatePdfOperationRequest {
    createPdfRequest: CreatePdfRequest;
}

/**
 * PDFApi - interface
 * 
 * @export
 * @interface PDFApiInterface
 */
export interface PDFApiInterface {
    /**
     * Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (`x-api-key` header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | `template_id` | string | ✅ Yes | Template short ID (12 characters) | | `data` | object | ✅ Yes | Key-value data to render in template | | `export_type` | string | No | `url` (default) or `binary` | | `expiration` | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - `url` (default): PDF is uploaded to CDN, returns JSON with URL - `binary`: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.
     * @summary Generate PDF from template
     * @param {CreatePdfRequest} createPdfRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFApiInterface
     */
    createPdfRaw(requestParameters: CreatePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePdfResponse>>;

    /**
     * Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (`x-api-key` header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | `template_id` | string | ✅ Yes | Template short ID (12 characters) | | `data` | object | ✅ Yes | Key-value data to render in template | | `export_type` | string | No | `url` (default) or `binary` | | `expiration` | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - `url` (default): PDF is uploaded to CDN, returns JSON with URL - `binary`: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.
     * Generate PDF from template
     */
    createPdf(createPdfRequest: CreatePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePdfResponse>;

}

/**
 * 
 */
export class PDFApi extends runtime.BaseAPI implements PDFApiInterface {

    /**
     * Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (`x-api-key` header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | `template_id` | string | ✅ Yes | Template short ID (12 characters) | | `data` | object | ✅ Yes | Key-value data to render in template | | `export_type` | string | No | `url` (default) or `binary` | | `expiration` | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - `url` (default): PDF is uploaded to CDN, returns JSON with URL - `binary`: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.
     * Generate PDF from template
     */
    async createPdfRaw(requestParameters: CreatePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePdfResponse>> {
        if (requestParameters['createPdfRequest'] == null) {
            throw new runtime.RequiredError(
                'createPdfRequest',
                'Required parameter "createPdfRequest" was null or undefined when calling createPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePdfRequestToJSON(requestParameters['createPdfRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePdfResponseFromJSON(jsonValue));
    }

    /**
     * Generate a PDF from a saved template with dynamic data.  **Authentication:** API Key required (`x-api-key` header)  ## Request Body  | Field | Type | Required | Description | |-------|------|----------|-------------| | `template_id` | string | ✅ Yes | Template short ID (12 characters) | | `data` | object | ✅ Yes | Key-value data to render in template | | `export_type` | string | No | `url` (default) or `binary` | | `expiration` | integer | No | URL expiration in seconds (60-604800, default: 86400) |  ## Export Types - `url` (default): PDF is uploaded to CDN, returns JSON with URL - `binary`: Returns raw PDF bytes directly  **Credits:** 1 credit deducted per successful generation.
     * Generate PDF from template
     */
    async createPdf(createPdfRequest: CreatePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePdfResponse> {
        const response = await this.createPdfRaw({ createPdfRequest: createPdfRequest }, initOverrides);
        return await response.value();
    }

}
