/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExtractPdfPagesRequest,
  MergePdfRequest,
  PdfToolsResponse,
  RotatePdfRequest,
} from '../models/index';
import {
    ExtractPdfPagesRequestFromJSON,
    ExtractPdfPagesRequestToJSON,
    MergePdfRequestFromJSON,
    MergePdfRequestToJSON,
    PdfToolsResponseFromJSON,
    PdfToolsResponseToJSON,
    RotatePdfRequestFromJSON,
    RotatePdfRequestToJSON,
} from '../models/index';

export interface ExtractPdfPagesOperationRequest {
    extractPdfPagesRequest: ExtractPdfPagesRequest;
}

export interface MergePdfOperationRequest {
    mergePdfRequest: MergePdfRequest;
}

export interface RotatePdfOperationRequest {
    rotatePdfRequest: RotatePdfRequest;
}

/**
 * PDFToolsApi - interface
 * 
 * @export
 * @interface PDFToolsApiInterface
 */
export interface PDFToolsApiInterface {
    /**
     * Creates request options for extractPdfPages without sending the request
     * @param {ExtractPdfPagesRequest} extractPdfPagesRequest 
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    extractPdfPagesRequestOpts(requestParameters: ExtractPdfPagesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (`1-3`) and singles (`5`). Order is preserved: `5,1,3` outputs those 3 pages in that order.  **Credits:** 1 credit per call.
     * @summary Extract pages from a PDF
     * @param {ExtractPdfPagesRequest} extractPdfPagesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    extractPdfPagesRaw(requestParameters: ExtractPdfPagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>>;

    /**
     * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (`1-3`) and singles (`5`). Order is preserved: `5,1,3` outputs those 3 pages in that order.  **Credits:** 1 credit per call.
     * Extract pages from a PDF
     */
    extractPdfPages(extractPdfPagesRequest: ExtractPdfPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse>;

    /**
     * Creates request options for mergePdf without sending the request
     * @param {MergePdfRequest} mergePdfRequest 
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    mergePdfRequestOpts(requestParameters: MergePdfOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
     * @summary Merge PDFs
     * @param {MergePdfRequest} mergePdfRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    mergePdfRaw(requestParameters: MergePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>>;

    /**
     * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
     * Merge PDFs
     */
    mergePdf(mergePdfRequest: MergePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse>;

    /**
     * Creates request options for rotatePdf without sending the request
     * @param {RotatePdfRequest} rotatePdfRequest 
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    rotatePdfRequestOpts(requestParameters: RotatePdfOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Rotate every page by the same angle (`rotation`), or apply a per-page rotation map (`page_rotations`). Rotations are cumulative with the page\'s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
     * @summary Rotate pages of a PDF
     * @param {RotatePdfRequest} rotatePdfRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PDFToolsApiInterface
     */
    rotatePdfRaw(requestParameters: RotatePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>>;

    /**
     * Rotate every page by the same angle (`rotation`), or apply a per-page rotation map (`page_rotations`). Rotations are cumulative with the page\'s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
     * Rotate pages of a PDF
     */
    rotatePdf(rotatePdfRequest: RotatePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse>;

}

/**
 * 
 */
export class PDFToolsApi extends runtime.BaseAPI implements PDFToolsApiInterface {

    /**
     * Creates request options for extractPdfPages without sending the request
     */
    async extractPdfPagesRequestOpts(requestParameters: ExtractPdfPagesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['extractPdfPagesRequest'] == null) {
            throw new runtime.RequiredError(
                'extractPdfPagesRequest',
                'Required parameter "extractPdfPagesRequest" was null or undefined when calling extractPdfPages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf-tools/extract-pages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExtractPdfPagesRequestToJSON(requestParameters['extractPdfPagesRequest']),
        };
    }

    /**
     * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (`1-3`) and singles (`5`). Order is preserved: `5,1,3` outputs those 3 pages in that order.  **Credits:** 1 credit per call.
     * Extract pages from a PDF
     */
    async extractPdfPagesRaw(requestParameters: ExtractPdfPagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>> {
        const requestOptions = await this.extractPdfPagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PdfToolsResponseFromJSON(jsonValue));
    }

    /**
     * Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (`1-3`) and singles (`5`). Order is preserved: `5,1,3` outputs those 3 pages in that order.  **Credits:** 1 credit per call.
     * Extract pages from a PDF
     */
    async extractPdfPages(extractPdfPagesRequest: ExtractPdfPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse> {
        const response = await this.extractPdfPagesRaw({ extractPdfPagesRequest: extractPdfPagesRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mergePdf without sending the request
     */
    async mergePdfRequestOpts(requestParameters: MergePdfOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mergePdfRequest'] == null) {
            throw new runtime.RequiredError(
                'mergePdfRequest',
                'Required parameter "mergePdfRequest" was null or undefined when calling mergePdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf-tools/merge`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MergePdfRequestToJSON(requestParameters['mergePdfRequest']),
        };
    }

    /**
     * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
     * Merge PDFs
     */
    async mergePdfRaw(requestParameters: MergePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>> {
        const requestOptions = await this.mergePdfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PdfToolsResponseFromJSON(jsonValue));
    }

    /**
     * Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
     * Merge PDFs
     */
    async mergePdf(mergePdfRequest: MergePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse> {
        const response = await this.mergePdfRaw({ mergePdfRequest: mergePdfRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotatePdf without sending the request
     */
    async rotatePdfRequestOpts(requestParameters: RotatePdfOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rotatePdfRequest'] == null) {
            throw new runtime.RequiredError(
                'rotatePdfRequest',
                'Required parameter "rotatePdfRequest" was null or undefined when calling rotatePdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/pdf-tools/rotate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RotatePdfRequestToJSON(requestParameters['rotatePdfRequest']),
        };
    }

    /**
     * Rotate every page by the same angle (`rotation`), or apply a per-page rotation map (`page_rotations`). Rotations are cumulative with the page\'s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
     * Rotate pages of a PDF
     */
    async rotatePdfRaw(requestParameters: RotatePdfOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PdfToolsResponse>> {
        const requestOptions = await this.rotatePdfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PdfToolsResponseFromJSON(jsonValue));
    }

    /**
     * Rotate every page by the same angle (`rotation`), or apply a per-page rotation map (`page_rotations`). Rotations are cumulative with the page\'s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
     * Rotate pages of a PDF
     */
    async rotatePdf(rotatePdfRequest: RotatePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PdfToolsResponse> {
        const response = await this.rotatePdfRaw({ rotatePdfRequest: rotatePdfRequest }, initOverrides);
        return await response.value();
    }

}
