/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  TemplateField,
  TemplatesListResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TemplateFieldFromJSON,
    TemplateFieldToJSON,
    TemplatesListResponseFromJSON,
    TemplatesListResponseToJSON,
} from '../models/index';

export interface GetTemplateFieldsRequest {
    templateId: string;
}

/**
 * TemplatesApi - interface
 * 
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for Zapier Dynamic Fields integration. It returns an array of field definitions that Zapier uses to dynamically generate input forms.  **Response format:** Array of objects compatible with Zapier InputFieldsSchema. Each field has: `key`, `label`, `type`, `required`, and optional `helpText`.  **Field types:** - `string`: Text input (also used for JSON arrays/objects) - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox  **Arrays and objects:** Complex types are returned as `string` type with a `helpText` showing the expected JSON format.  **No credits consumed:** This is a read-only endpoint.
     * @summary Get template fields
     * @param {string} templateId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    getTemplateFieldsRaw(requestParameters: GetTemplateFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplateField>>>;

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for Zapier Dynamic Fields integration. It returns an array of field definitions that Zapier uses to dynamically generate input forms.  **Response format:** Array of objects compatible with Zapier InputFieldsSchema. Each field has: `key`, `label`, `type`, `required`, and optional `helpText`.  **Field types:** - `string`: Text input (also used for JSON arrays/objects) - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox  **Arrays and objects:** Complex types are returned as `string` type with a `helpText` showing the expected JSON format.  **No credits consumed:** This is a read-only endpoint.
     * Get template fields
     */
    getTemplateFields(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplateField>>;

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.
     * @summary List templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesListResponse>>;

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.
     * List templates
     */
    listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesListResponse>;

}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for Zapier Dynamic Fields integration. It returns an array of field definitions that Zapier uses to dynamically generate input forms.  **Response format:** Array of objects compatible with Zapier InputFieldsSchema. Each field has: `key`, `label`, `type`, `required`, and optional `helpText`.  **Field types:** - `string`: Text input (also used for JSON arrays/objects) - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox  **Arrays and objects:** Complex types are returned as `string` type with a `helpText` showing the expected JSON format.  **No credits consumed:** This is a read-only endpoint.
     * Get template fields
     */
    async getTemplateFieldsRaw(requestParameters: GetTemplateFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplateField>>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getTemplateFields().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/fields`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TemplateFieldFromJSON));
    }

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for Zapier Dynamic Fields integration. It returns an array of field definitions that Zapier uses to dynamically generate input forms.  **Response format:** Array of objects compatible with Zapier InputFieldsSchema. Each field has: `key`, `label`, `type`, `required`, and optional `helpText`.  **Field types:** - `string`: Text input (also used for JSON arrays/objects) - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox  **Arrays and objects:** Complex types are returned as `string` type with a `helpText` showing the expected JSON format.  **No credits consumed:** This is a read-only endpoint.
     * Get template fields
     */
    async getTemplateFields(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplateField>> {
        const response = await this.getTemplateFieldsRaw({ templateId: templateId }, initOverrides);
        return await response.value();
    }

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.
     * List templates
     */
    async listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesListResponseFromJSON(jsonValue));
    }

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.
     * List templates
     */
    async listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesListResponse> {
        const response = await this.listTemplatesRaw(initOverrides);
        return await response.value();
    }

}
