/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVersionRequest,
  HTTPValidationError,
  TemplateField,
  TemplatesListResponse,
  UpdateVersionRequest,
  VersionItem,
  VersionsListResponse,
} from '../models/index';
import {
    CreateVersionRequestFromJSON,
    CreateVersionRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TemplateFieldFromJSON,
    TemplateFieldToJSON,
    TemplatesListResponseFromJSON,
    TemplatesListResponseToJSON,
    UpdateVersionRequestFromJSON,
    UpdateVersionRequestToJSON,
    VersionItemFromJSON,
    VersionItemToJSON,
    VersionsListResponseFromJSON,
    VersionsListResponseToJSON,
} from '../models/index';

export interface CreateTemplateVersionRequest {
    templateId: string;
    createVersionRequest: CreateVersionRequest;
}

export interface DeleteTemplateVersionRequest {
    templateId: string;
    versionNumber: number;
}

export interface GetTemplateFieldsRequest {
    templateId: string;
}

export interface ListTemplateVersionsRequest {
    templateId: string;
}

export interface UpdateTemplateVersionRequest {
    templateId: string;
    versionNumber: number;
    updateVersionRequest: UpdateVersionRequest;
}

/**
 * TemplatesApi - interface
 * 
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     * Creates request options for createTemplateVersion without sending the request
     * @param {string} templateId Template short ID (12 characters)
     * @param {CreateVersionRequest} createVersionRequest 
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    createTemplateVersionRequestOpts(requestParameters: CreateTemplateVersionRequest): Promise<runtime.RequestOpts>;

    /**
     * Create an immutable snapshot of the current template draft.
     * @summary Create a version snapshot
     * @param {string} templateId Template short ID (12 characters)
     * @param {CreateVersionRequest} createVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    createTemplateVersionRaw(requestParameters: CreateTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionItem>>;

    /**
     * Create an immutable snapshot of the current template draft.
     * Create a version snapshot
     */
    createTemplateVersion(templateId: string, createVersionRequest: CreateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionItem>;

    /**
     * Creates request options for deleteTemplateVersion without sending the request
     * @param {string} templateId Template short ID
     * @param {number} versionNumber Version number to delete
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    deleteTemplateVersionRequestOpts(requestParameters: DeleteTemplateVersionRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a specific version snapshot.
     * @summary Delete a version
     * @param {string} templateId Template short ID
     * @param {number} versionNumber Version number to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    deleteTemplateVersionRaw(requestParameters: DeleteTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Delete a specific version snapshot.
     * Delete a version
     */
    deleteTemplateVersion(templateId: string, versionNumber: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for getTemplateFields without sending the request
     * @param {string} templateId Template short ID (12 characters)
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    getTemplateFieldsRequestOpts(requestParameters: GetTemplateFieldsRequest): Promise<runtime.RequestOpts>;

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: `key`, `label`, `type`, `required`, optional `helpText`, and optional `spec` (for array fields).  **Field types:** - `string`: Text input - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox - `array`: Array of items with nested `spec` defining item structure  **Array fields:** When a field is an array of objects, the response includes a `spec` array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary Get template fields
     * @param {string} templateId Template short ID (12 characters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    getTemplateFieldsRaw(requestParameters: GetTemplateFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplateField>>>;

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: `key`, `label`, `type`, `required`, optional `helpText`, and optional `spec` (for array fields).  **Field types:** - `string`: Text input - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox - `array`: Array of items with nested `spec` defining item structure  **Array fields:** When a field is an array of objects, the response includes a `spec` array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get template fields
     */
    getTemplateFields(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplateField>>;

    /**
     * Creates request options for listTemplateVersions without sending the request
     * @param {string} templateId Template short ID (12 characters)
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    listTemplateVersionsRequestOpts(requestParameters: ListTemplateVersionsRequest): Promise<runtime.RequestOpts>;

    /**
     * List all snapshot versions for a template (excludes the working draft).
     * @summary List template versions
     * @param {string} templateId Template short ID (12 characters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    listTemplateVersionsRaw(requestParameters: ListTemplateVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionsListResponse>>;

    /**
     * List all snapshot versions for a template (excludes the working draft).
     * List template versions
     */
    listTemplateVersions(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionsListResponse>;

    /**
     * Creates request options for listTemplates without sending the request
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    listTemplatesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * @summary List templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesListResponse>>;

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * List templates
     */
    listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesListResponse>;

    /**
     * Creates request options for updateTemplateVersion without sending the request
     * @param {string} templateId Template short ID
     * @param {number} versionNumber Version number to update
     * @param {UpdateVersionRequest} updateVersionRequest 
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    updateTemplateVersionRequestOpts(requestParameters: UpdateTemplateVersionRequest): Promise<runtime.RequestOpts>;

    /**
     * Update a version\'s tag or description.
     * @summary Update a version
     * @param {string} templateId Template short ID
     * @param {number} versionNumber Version number to update
     * @param {UpdateVersionRequest} updateVersionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    updateTemplateVersionRaw(requestParameters: UpdateTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionItem>>;

    /**
     * Update a version\'s tag or description.
     * Update a version
     */
    updateTemplateVersion(templateId: string, versionNumber: number, updateVersionRequest: UpdateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionItem>;

}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {

    /**
     * Creates request options for createTemplateVersion without sending the request
     */
    async createTemplateVersionRequestOpts(requestParameters: CreateTemplateVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling createTemplateVersion().'
            );
        }

        if (requestParameters['createVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'createVersionRequest',
                'Required parameter "createVersionRequest" was null or undefined when calling createTemplateVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/versions`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVersionRequestToJSON(requestParameters['createVersionRequest']),
        };
    }

    /**
     * Create an immutable snapshot of the current template draft.
     * Create a version snapshot
     */
    async createTemplateVersionRaw(requestParameters: CreateTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionItem>> {
        const requestOptions = await this.createTemplateVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionItemFromJSON(jsonValue));
    }

    /**
     * Create an immutable snapshot of the current template draft.
     * Create a version snapshot
     */
    async createTemplateVersion(templateId: string, createVersionRequest: CreateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionItem> {
        const response = await this.createTemplateVersionRaw({ templateId: templateId, createVersionRequest: createVersionRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTemplateVersion without sending the request
     */
    async deleteTemplateVersionRequestOpts(requestParameters: DeleteTemplateVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling deleteTemplateVersion().'
            );
        }

        if (requestParameters['versionNumber'] == null) {
            throw new runtime.RequiredError(
                'versionNumber',
                'Required parameter "versionNumber" was null or undefined when calling deleteTemplateVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/versions/{version_number}`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));
        urlPath = urlPath.replace(`{${"version_number"}}`, encodeURIComponent(String(requestParameters['versionNumber'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a specific version snapshot.
     * Delete a version
     */
    async deleteTemplateVersionRaw(requestParameters: DeleteTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deleteTemplateVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a specific version snapshot.
     * Delete a version
     */
    async deleteTemplateVersion(templateId: string, versionNumber: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteTemplateVersionRaw({ templateId: templateId, versionNumber: versionNumber }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTemplateFields without sending the request
     */
    async getTemplateFieldsRequestOpts(requestParameters: GetTemplateFieldsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getTemplateFields().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/fields`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: `key`, `label`, `type`, `required`, optional `helpText`, and optional `spec` (for array fields).  **Field types:** - `string`: Text input - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox - `array`: Array of items with nested `spec` defining item structure  **Array fields:** When a field is an array of objects, the response includes a `spec` array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get template fields
     */
    async getTemplateFieldsRaw(requestParameters: GetTemplateFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TemplateField>>> {
        const requestOptions = await this.getTemplateFieldsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TemplateFieldFromJSON));
    }

    /**
     * Get the dynamic fields for a template.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tool integrations (Zapier, Make.com). It returns an array of field definitions used to dynamically generate input forms.  **Response format:** Array of field objects with: `key`, `label`, `type`, `required`, optional `helpText`, and optional `spec` (for array fields).  **Field types:** - `string`: Text input - `integer`: Integer number - `number`: Decimal number - `boolean`: True/False checkbox - `array`: Array of items with nested `spec` defining item structure  **Array fields:** When a field is an array of objects, the response includes a `spec` array defining the structure of each item (name, label, type for each nested field).  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * Get template fields
     */
    async getTemplateFields(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TemplateField>> {
        const response = await this.getTemplateFieldsRaw({ templateId: templateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTemplateVersions without sending the request
     */
    async listTemplateVersionsRequestOpts(requestParameters: ListTemplateVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling listTemplateVersions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/versions`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all snapshot versions for a template (excludes the working draft).
     * List template versions
     */
    async listTemplateVersionsRaw(requestParameters: ListTemplateVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionsListResponse>> {
        const requestOptions = await this.listTemplateVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionsListResponseFromJSON(jsonValue));
    }

    /**
     * List all snapshot versions for a template (excludes the working draft).
     * List template versions
     */
    async listTemplateVersions(templateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionsListResponse> {
        const response = await this.listTemplateVersionsRaw({ templateId: templateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTemplates without sending the request
     */
    async listTemplatesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * List templates
     */
    async listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesListResponse>> {
        const requestOptions = await this.listTemplatesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesListResponseFromJSON(jsonValue));
    }

    /**
     * List all templates for the authenticated user.  **Authentication:** API Key required (`x-api-key` header) or JWT token  **Usage:** This endpoint is designed for no-code tools (Zapier, Make, n8n) to populate template selection dropdowns.  **No credits consumed:** This is a read-only endpoint.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
     * List templates
     */
    async listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesListResponse> {
        const response = await this.listTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTemplateVersion without sending the request
     */
    async updateTemplateVersionRequestOpts(requestParameters: UpdateTemplateVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling updateTemplateVersion().'
            );
        }

        if (requestParameters['versionNumber'] == null) {
            throw new runtime.RequiredError(
                'versionNumber',
                'Required parameter "versionNumber" was null or undefined when calling updateTemplateVersion().'
            );
        }

        if (requestParameters['updateVersionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateVersionRequest',
                'Required parameter "updateVersionRequest" was null or undefined when calling updateTemplateVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/templates/{template_id}/versions/{version_number}`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));
        urlPath = urlPath.replace(`{${"version_number"}}`, encodeURIComponent(String(requestParameters['versionNumber'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVersionRequestToJSON(requestParameters['updateVersionRequest']),
        };
    }

    /**
     * Update a version\'s tag or description.
     * Update a version
     */
    async updateTemplateVersionRaw(requestParameters: UpdateTemplateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionItem>> {
        const requestOptions = await this.updateTemplateVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionItemFromJSON(jsonValue));
    }

    /**
     * Update a version\'s tag or description.
     * Update a version
     */
    async updateTemplateVersion(templateId: string, versionNumber: number, updateVersionRequest: UpdateVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionItem> {
        const response = await this.updateTemplateVersionRaw({ templateId: templateId, versionNumber: versionNumber, updateVersionRequest: updateVersionRequest }, initOverrides);
        return await response.value();
    }

}
