/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for account info endpoint
 * @export
 * @interface AccountInfoResponse
 */
export interface AccountInfoResponse {
    /**
     * Remaining credits
     * @type {number}
     * @memberof AccountInfoResponse
     */
    credits: number;
    /**
     * 
     * @type {string}
     * @memberof AccountInfoResponse
     */
    email?: string | null;
}

/**
 * Check if a given object implements the AccountInfoResponse interface.
 */
export function instanceOfAccountInfoResponse(value: object): value is AccountInfoResponse {
    if (!('credits' in value) || value['credits'] === undefined) return false;
    return true;
}

export function AccountInfoResponseFromJSON(json: any): AccountInfoResponse {
    return AccountInfoResponseFromJSONTyped(json, false);
}

export function AccountInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'credits': json['credits'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function AccountInfoResponseToJSON(json: any): AccountInfoResponse {
    return AccountInfoResponseToJSONTyped(json, false);
}

export function AccountInfoResponseToJSONTyped(value?: AccountInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credits': value['credits'],
        'email': value['email'],
    };
}

