/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PDF export type options
 * @export
 */
export const AppRoutersV1PdfExportType = {
    Url: 'url',
    Binary: 'binary'
} as const;
export type AppRoutersV1PdfExportType = typeof AppRoutersV1PdfExportType[keyof typeof AppRoutersV1PdfExportType];


export function instanceOfAppRoutersV1PdfExportType(value: any): boolean {
    for (const key in AppRoutersV1PdfExportType) {
        if (Object.prototype.hasOwnProperty.call(AppRoutersV1PdfExportType, key)) {
            if (AppRoutersV1PdfExportType[key as keyof typeof AppRoutersV1PdfExportType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppRoutersV1PdfExportTypeFromJSON(json: any): AppRoutersV1PdfExportType {
    return AppRoutersV1PdfExportTypeFromJSONTyped(json, false);
}

export function AppRoutersV1PdfExportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoutersV1PdfExportType {
    return json as AppRoutersV1PdfExportType;
}

export function AppRoutersV1PdfExportTypeToJSON(value?: AppRoutersV1PdfExportType | null): any {
    return value as any;
}

export function AppRoutersV1PdfExportTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AppRoutersV1PdfExportType {
    return value as AppRoutersV1PdfExportType;
}

