/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppRoutersV1PdfToolsExportType = {
    Url: 'url',
    Binary: 'binary'
} as const;
export type AppRoutersV1PdfToolsExportType = typeof AppRoutersV1PdfToolsExportType[keyof typeof AppRoutersV1PdfToolsExportType];


export function instanceOfAppRoutersV1PdfToolsExportType(value: any): boolean {
    for (const key in AppRoutersV1PdfToolsExportType) {
        if (Object.prototype.hasOwnProperty.call(AppRoutersV1PdfToolsExportType, key)) {
            if (AppRoutersV1PdfToolsExportType[key as keyof typeof AppRoutersV1PdfToolsExportType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppRoutersV1PdfToolsExportTypeFromJSON(json: any): AppRoutersV1PdfToolsExportType {
    return AppRoutersV1PdfToolsExportTypeFromJSONTyped(json, false);
}

export function AppRoutersV1PdfToolsExportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoutersV1PdfToolsExportType {
    return json as AppRoutersV1PdfToolsExportType;
}

export function AppRoutersV1PdfToolsExportTypeToJSON(value?: AppRoutersV1PdfToolsExportType | null): any {
    return value as any;
}

export function AppRoutersV1PdfToolsExportTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AppRoutersV1PdfToolsExportType {
    return value as AppRoutersV1PdfToolsExportType;
}

