/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PDF export type options for async generation
 * @export
 */
export const AppRoutersV1PdfAsyncExportType = {
    Url: 'url'
} as const;
export type AppRoutersV1PdfAsyncExportType = typeof AppRoutersV1PdfAsyncExportType[keyof typeof AppRoutersV1PdfAsyncExportType];


export function instanceOfAppRoutersV1PdfAsyncExportType(value: any): boolean {
    for (const key in AppRoutersV1PdfAsyncExportType) {
        if (Object.prototype.hasOwnProperty.call(AppRoutersV1PdfAsyncExportType, key)) {
            if (AppRoutersV1PdfAsyncExportType[key as keyof typeof AppRoutersV1PdfAsyncExportType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppRoutersV1PdfAsyncExportTypeFromJSON(json: any): AppRoutersV1PdfAsyncExportType {
    return AppRoutersV1PdfAsyncExportTypeFromJSONTyped(json, false);
}

export function AppRoutersV1PdfAsyncExportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoutersV1PdfAsyncExportType {
    return json as AppRoutersV1PdfAsyncExportType;
}

export function AppRoutersV1PdfAsyncExportTypeToJSON(value?: AppRoutersV1PdfAsyncExportType | null): any {
    return value as any;
}

export function AppRoutersV1PdfAsyncExportTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AppRoutersV1PdfAsyncExportType {
    return value as AppRoutersV1PdfAsyncExportType;
}

