/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for URL export type
 * @export
 * @interface CreatePdfResponse
 */
export interface CreatePdfResponse {
    /**
     * Signed URL to download the PDF (expires after specified time)
     * @type {string}
     * @memberof CreatePdfResponse
     */
    url: string;
    /**
     * Filename of the generated PDF
     * @type {string}
     * @memberof CreatePdfResponse
     */
    filename: string;
    /**
     * Remaining credits after this request
     * @type {number}
     * @memberof CreatePdfResponse
     */
    creditsRemaining: number;
    /**
     * Seconds until URL expires
     * @type {number}
     * @memberof CreatePdfResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the CreatePdfResponse interface.
 */
export function instanceOfCreatePdfResponse(value: object): value is CreatePdfResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('creditsRemaining' in value) || value['creditsRemaining'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function CreatePdfResponseFromJSON(json: any): CreatePdfResponse {
    return CreatePdfResponseFromJSONTyped(json, false);
}

export function CreatePdfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePdfResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'filename': json['filename'],
        'creditsRemaining': json['credits_remaining'],
        'expiresIn': json['expires_in'],
    };
}

export function CreatePdfResponseToJSON(json: any): CreatePdfResponse {
    return CreatePdfResponseToJSONTyped(json, false);
}

export function CreatePdfResponseToJSONTyped(value?: CreatePdfResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'filename': value['filename'],
        'credits_remaining': value['creditsRemaining'],
        'expires_in': value['expiresIn'],
    };
}

