/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoutersV1PdfExportType } from './AppRoutersV1PdfExportType';
import {
    AppRoutersV1PdfExportTypeFromJSON,
    AppRoutersV1PdfExportTypeFromJSONTyped,
    AppRoutersV1PdfExportTypeToJSON,
    AppRoutersV1PdfExportTypeToJSONTyped,
} from './AppRoutersV1PdfExportType';

/**
 * Request model for PDF generation
 * @export
 * @interface CreatePdfRequest
 */
export interface CreatePdfRequest {
    /**
     * **Required.** Template short ID (12 characters)
     * @type {string}
     * @memberof CreatePdfRequest
     */
    templateId: string;
    /**
     * **Required.** Key-value data to render in the template. Keys must match template variables.
     * @type {{ [key: string]: any; }}
     * @memberof CreatePdfRequest
     */
    data: { [key: string]: any; };
    /**
     * Export format: `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
     * @type {AppRoutersV1PdfExportType}
     * @memberof CreatePdfRequest
     */
    exportType?: AppRoutersV1PdfExportType;
    /**
     * URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to `url` export type.
     * @type {number}
     * @memberof CreatePdfRequest
     */
    expiration?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePdfRequest
     */
    filename?: string | null;
    /**
     * Upload to your configured S3 bucket instead of CDN
     * @type {boolean}
     * @memberof CreatePdfRequest
     */
    storeS3?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatePdfRequest
     */
    s3Filepath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePdfRequest
     */
    s3Bucket?: string | null;
}



/**
 * Check if a given object implements the CreatePdfRequest interface.
 */
export function instanceOfCreatePdfRequest(value: object): value is CreatePdfRequest {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreatePdfRequestFromJSON(json: any): CreatePdfRequest {
    return CreatePdfRequestFromJSONTyped(json, false);
}

export function CreatePdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'],
        'data': json['data'],
        'exportType': json['export_type'] == null ? undefined : AppRoutersV1PdfExportTypeFromJSON(json['export_type']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'storeS3': json['store_s3'] == null ? undefined : json['store_s3'],
        's3Filepath': json['s3_filepath'] == null ? undefined : json['s3_filepath'],
        's3Bucket': json['s3_bucket'] == null ? undefined : json['s3_bucket'],
    };
}

export function CreatePdfRequestToJSON(json: any): CreatePdfRequest {
    return CreatePdfRequestToJSONTyped(json, false);
}

export function CreatePdfRequestToJSONTyped(value?: CreatePdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['templateId'],
        'data': value['data'],
        'export_type': AppRoutersV1PdfExportTypeToJSON(value['exportType']),
        'expiration': value['expiration'],
        'filename': value['filename'],
        'store_s3': value['storeS3'],
        's3_filepath': value['s3Filepath'],
        's3_bucket': value['s3Bucket'],
    };
}

