/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoutersV1PdfAsyncExportType } from './AppRoutersV1PdfAsyncExportType';
import {
    AppRoutersV1PdfAsyncExportTypeFromJSON,
    AppRoutersV1PdfAsyncExportTypeFromJSONTyped,
    AppRoutersV1PdfAsyncExportTypeToJSON,
    AppRoutersV1PdfAsyncExportTypeToJSONTyped,
} from './AppRoutersV1PdfAsyncExportType';

/**
 * Request model for async PDF generation
 * @export
 * @interface CreateAsyncPdfRequest
 */
export interface CreateAsyncPdfRequest {
    /**
     * **Required.** Template short ID (12 characters)
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    templateId: string;
    /**
     * **Required.** Key-value data to render in the template.
     * @type {{ [key: string]: any; }}
     * @memberof CreateAsyncPdfRequest
     */
    data: { [key: string]: any; };
    /**
     * Export format. Currently only `url` is supported for async.
     * @type {AppRoutersV1PdfAsyncExportType}
     * @memberof CreateAsyncPdfRequest
     */
    exportType?: AppRoutersV1PdfAsyncExportType;
    /**
     * URL expiration in seconds (60-604800). Default: 86400 (24 hours).
     * @type {number}
     * @memberof CreateAsyncPdfRequest
     */
    expiration?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    filename?: string | null;
    /**
     * Upload to your configured S3 bucket instead of CDN.
     * @type {boolean}
     * @memberof CreateAsyncPdfRequest
     */
    storeS3?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    s3Filepath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    s3Bucket?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    webhookUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAsyncPdfRequest
     */
    webhookSecret?: string | null;
}



/**
 * Check if a given object implements the CreateAsyncPdfRequest interface.
 */
export function instanceOfCreateAsyncPdfRequest(value: object): value is CreateAsyncPdfRequest {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateAsyncPdfRequestFromJSON(json: any): CreateAsyncPdfRequest {
    return CreateAsyncPdfRequestFromJSONTyped(json, false);
}

export function CreateAsyncPdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAsyncPdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'],
        'data': json['data'],
        'exportType': json['export_type'] == null ? undefined : AppRoutersV1PdfAsyncExportTypeFromJSON(json['export_type']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'storeS3': json['store_s3'] == null ? undefined : json['store_s3'],
        's3Filepath': json['s3_filepath'] == null ? undefined : json['s3_filepath'],
        's3Bucket': json['s3_bucket'] == null ? undefined : json['s3_bucket'],
        'webhookUrl': json['webhook_url'] == null ? undefined : json['webhook_url'],
        'webhookSecret': json['webhook_secret'] == null ? undefined : json['webhook_secret'],
    };
}

export function CreateAsyncPdfRequestToJSON(json: any): CreateAsyncPdfRequest {
    return CreateAsyncPdfRequestToJSONTyped(json, false);
}

export function CreateAsyncPdfRequestToJSONTyped(value?: CreateAsyncPdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['templateId'],
        'data': value['data'],
        'export_type': AppRoutersV1PdfAsyncExportTypeToJSON(value['exportType']),
        'expiration': value['expiration'],
        'filename': value['filename'],
        'store_s3': value['storeS3'],
        's3_filepath': value['s3Filepath'],
        's3_bucket': value['s3Bucket'],
        'webhook_url': value['webhookUrl'],
        'webhook_secret': value['webhookSecret'],
    };
}

