/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * Response for async PDF creation
 * @export
 * @interface CreateAsyncPdfResponse
 */
export interface CreateAsyncPdfResponse {
    /**
     * Unique job identifier for status polling
     * @type {string}
     * @memberof CreateAsyncPdfResponse
     */
    jobId: string;
    /**
     * Initial job status (always 'pending')
     * @type {JobStatus}
     * @memberof CreateAsyncPdfResponse
     */
    status: JobStatus;
    /**
     * Remaining credits after this request
     * @type {number}
     * @memberof CreateAsyncPdfResponse
     */
    creditsRemaining: number;
}



/**
 * Check if a given object implements the CreateAsyncPdfResponse interface.
 */
export function instanceOfCreateAsyncPdfResponse(value: object): value is CreateAsyncPdfResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('creditsRemaining' in value) || value['creditsRemaining'] === undefined) return false;
    return true;
}

export function CreateAsyncPdfResponseFromJSON(json: any): CreateAsyncPdfResponse {
    return CreateAsyncPdfResponseFromJSONTyped(json, false);
}

export function CreateAsyncPdfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAsyncPdfResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': JobStatusFromJSON(json['status']),
        'creditsRemaining': json['credits_remaining'],
    };
}

export function CreateAsyncPdfResponseToJSON(json: any): CreateAsyncPdfResponse {
    return CreateAsyncPdfResponseToJSONTyped(json, false);
}

export function CreateAsyncPdfResponseToJSONTyped(value?: CreateAsyncPdfResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': JobStatusToJSON(value['status']),
        'credits_remaining': value['creditsRemaining'],
    };
}

