/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to create a version snapshot
 * @export
 * @interface CreateVersionRequest
 */
export interface CreateVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateVersionRequest
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateVersionRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateVersionRequest interface.
 */
export function instanceOfCreateVersionRequest(value: object): value is CreateVersionRequest {
    return true;
}

export function CreateVersionRequestFromJSON(json: any): CreateVersionRequest {
    return CreateVersionRequestFromJSONTyped(json, false);
}

export function CreateVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateVersionRequestToJSON(json: any): CreateVersionRequest {
    return CreateVersionRequestToJSONTyped(json, false);
}

export function CreateVersionRequestToJSONTyped(value?: CreateVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'description': value['description'],
    };
}

