/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoutersV1PdfToolsExportType } from './AppRoutersV1PdfToolsExportType';
import {
    AppRoutersV1PdfToolsExportTypeFromJSON,
    AppRoutersV1PdfToolsExportTypeFromJSONTyped,
    AppRoutersV1PdfToolsExportTypeToJSON,
    AppRoutersV1PdfToolsExportTypeToJSONTyped,
} from './AppRoutersV1PdfToolsExportType';

/**
 * 
 * @export
 * @interface ExtractPdfPagesRequest
 */
export interface ExtractPdfPagesRequest {
    /**
     * `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
     * @type {AppRoutersV1PdfToolsExportType}
     * @memberof ExtractPdfPagesRequest
     */
    exportType?: AppRoutersV1PdfToolsExportType;
    /**
     * URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
     * @type {number}
     * @memberof ExtractPdfPagesRequest
     */
    expiration?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtractPdfPagesRequest
     */
    filename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtractPdfPagesRequest
     */
    pdfUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExtractPdfPagesRequest
     */
    pdfBase64?: string | null;
    /**
     * 1-indexed page selection. Supports ranges and singles separated by commas, e.g. `1-3, 5, 7-9`. Order is preserved (`5,1,3` outputs those 3 pages in that order).
     * @type {string}
     * @memberof ExtractPdfPagesRequest
     */
    pages: string;
}



/**
 * Check if a given object implements the ExtractPdfPagesRequest interface.
 */
export function instanceOfExtractPdfPagesRequest(value: object): value is ExtractPdfPagesRequest {
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function ExtractPdfPagesRequestFromJSON(json: any): ExtractPdfPagesRequest {
    return ExtractPdfPagesRequestFromJSONTyped(json, false);
}

export function ExtractPdfPagesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractPdfPagesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exportType': json['export_type'] == null ? undefined : AppRoutersV1PdfToolsExportTypeFromJSON(json['export_type']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'pdfUrl': json['pdf_url'] == null ? undefined : json['pdf_url'],
        'pdfBase64': json['pdf_base64'] == null ? undefined : json['pdf_base64'],
        'pages': json['pages'],
    };
}

export function ExtractPdfPagesRequestToJSON(json: any): ExtractPdfPagesRequest {
    return ExtractPdfPagesRequestToJSONTyped(json, false);
}

export function ExtractPdfPagesRequestToJSONTyped(value?: ExtractPdfPagesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'export_type': AppRoutersV1PdfToolsExportTypeToJSON(value['exportType']),
        'expiration': value['expiration'],
        'filename': value['filename'],
        'pdf_url': value['pdfUrl'],
        'pdf_base64': value['pdfBase64'],
        'pages': value['pages'],
    };
}

