/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatusResponse } from './JobStatusResponse';
import {
    JobStatusResponseFromJSON,
    JobStatusResponseFromJSONTyped,
    JobStatusResponseToJSON,
    JobStatusResponseToJSONTyped,
} from './JobStatusResponse';

/**
 * Response for job list query
 * @export
 * @interface JobListResponse
 */
export interface JobListResponse {
    /**
     * List of jobs
     * @type {Array<JobStatusResponse>}
     * @memberof JobListResponse
     */
    jobs: Array<JobStatusResponse>;
    /**
     * Total number of jobs matching filter
     * @type {number}
     * @memberof JobListResponse
     */
    total: number;
    /**
     * Page size
     * @type {number}
     * @memberof JobListResponse
     */
    limit: number;
    /**
     * Page offset
     * @type {number}
     * @memberof JobListResponse
     */
    offset: number;
}

/**
 * Check if a given object implements the JobListResponse interface.
 */
export function instanceOfJobListResponse(value: object): value is JobListResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function JobListResponseFromJSON(json: any): JobListResponse {
    return JobListResponseFromJSONTyped(json, false);
}

export function JobListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(JobStatusResponseFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function JobListResponseToJSON(json: any): JobListResponse {
    return JobListResponseToJSONTyped(json, false);
}

export function JobListResponseToJSONTyped(value?: JobListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(JobStatusResponseToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

