/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * Response for job status query
 * @export
 * @interface JobStatusResponse
 */
export interface JobStatusResponse {
    /**
     * Job ID
     * @type {string}
     * @memberof JobStatusResponse
     */
    id: string;
    /**
     * Current job status
     * @type {JobStatus}
     * @memberof JobStatusResponse
     */
    status: JobStatus;
    /**
     * Template used for generation
     * @type {string}
     * @memberof JobStatusResponse
     */
    templateId: string;
    /**
     * Export type (url)
     * @type {string}
     * @memberof JobStatusResponse
     */
    exportType: string;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    filename?: string | null;
    /**
     * Whether S3 storage was requested
     * @type {boolean}
     * @memberof JobStatusResponse
     */
    storeS3: boolean;
    /**
     * Job creation timestamp (ISO 8601)
     * @type {string}
     * @memberof JobStatusResponse
     */
    createdAt: string;
    /**
     * Last update timestamp (ISO 8601)
     * @type {string}
     * @memberof JobStatusResponse
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    completedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    resultUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    resultFilename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    resultExpiresAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    resultS3Bucket?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    resultS3Key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    errorCode?: string | null;
}



/**
 * Check if a given object implements the JobStatusResponse interface.
 */
export function instanceOfJobStatusResponse(value: object): value is JobStatusResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('exportType' in value) || value['exportType'] === undefined) return false;
    if (!('storeS3' in value) || value['storeS3'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function JobStatusResponseFromJSON(json: any): JobStatusResponse {
    return JobStatusResponseFromJSONTyped(json, false);
}

export function JobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': JobStatusFromJSON(json['status']),
        'templateId': json['template_id'],
        'exportType': json['export_type'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'storeS3': json['store_s3'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
        'resultUrl': json['result_url'] == null ? undefined : json['result_url'],
        'resultFilename': json['result_filename'] == null ? undefined : json['result_filename'],
        'resultExpiresAt': json['result_expires_at'] == null ? undefined : json['result_expires_at'],
        'resultS3Bucket': json['result_s3_bucket'] == null ? undefined : json['result_s3_bucket'],
        'resultS3Key': json['result_s3_key'] == null ? undefined : json['result_s3_key'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'errorCode': json['error_code'] == null ? undefined : json['error_code'],
    };
}

export function JobStatusResponseToJSON(json: any): JobStatusResponse {
    return JobStatusResponseToJSONTyped(json, false);
}

export function JobStatusResponseToJSONTyped(value?: JobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': JobStatusToJSON(value['status']),
        'template_id': value['templateId'],
        'export_type': value['exportType'],
        'filename': value['filename'],
        'store_s3': value['storeS3'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'completed_at': value['completedAt'],
        'result_url': value['resultUrl'],
        'result_filename': value['resultFilename'],
        'result_expires_at': value['resultExpiresAt'],
        'result_s3_bucket': value['resultS3Bucket'],
        'result_s3_key': value['resultS3Key'],
        'error_message': value['errorMessage'],
        'error_code': value['errorCode'],
    };
}

