/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoutersV1PdfToolsExportType } from './AppRoutersV1PdfToolsExportType';
import {
    AppRoutersV1PdfToolsExportTypeFromJSON,
    AppRoutersV1PdfToolsExportTypeFromJSONTyped,
    AppRoutersV1PdfToolsExportTypeToJSON,
    AppRoutersV1PdfToolsExportTypeToJSONTyped,
} from './AppRoutersV1PdfToolsExportType';
import type { PdfInput } from './PdfInput';
import {
    PdfInputFromJSON,
    PdfInputFromJSONTyped,
    PdfInputToJSON,
    PdfInputToJSONTyped,
} from './PdfInput';

/**
 * 
 * @export
 * @interface MergePdfRequest
 */
export interface MergePdfRequest {
    /**
     * `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
     * @type {AppRoutersV1PdfToolsExportType}
     * @memberof MergePdfRequest
     */
    exportType?: AppRoutersV1PdfToolsExportType;
    /**
     * URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
     * @type {number}
     * @memberof MergePdfRequest
     */
    expiration?: number;
    /**
     * 
     * @type {string}
     * @memberof MergePdfRequest
     */
    filename?: string | null;
    /**
     * Ordered list of PDFs to merge. Each entry has either `pdf_url` or `pdf_base64`. Minimum 2.
     * @type {Array<PdfInput>}
     * @memberof MergePdfRequest
     */
    pdfs: Array<PdfInput>;
}



/**
 * Check if a given object implements the MergePdfRequest interface.
 */
export function instanceOfMergePdfRequest(value: object): value is MergePdfRequest {
    if (!('pdfs' in value) || value['pdfs'] === undefined) return false;
    return true;
}

export function MergePdfRequestFromJSON(json: any): MergePdfRequest {
    return MergePdfRequestFromJSONTyped(json, false);
}

export function MergePdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergePdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exportType': json['export_type'] == null ? undefined : AppRoutersV1PdfToolsExportTypeFromJSON(json['export_type']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'pdfs': ((json['pdfs'] as Array<any>).map(PdfInputFromJSON)),
    };
}

export function MergePdfRequestToJSON(json: any): MergePdfRequest {
    return MergePdfRequestToJSONTyped(json, false);
}

export function MergePdfRequestToJSONTyped(value?: MergePdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'export_type': AppRoutersV1PdfToolsExportTypeToJSON(value['exportType']),
        'expiration': value['expiration'],
        'filename': value['filename'],
        'pdfs': ((value['pdfs'] as Array<any>).map(PdfInputToJSON)),
    };
}

