/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Either pdf_url (HTTPS) or pdf_base64 — exactly one.
 * @export
 * @interface PdfInput
 */
export interface PdfInput {
    /**
     * 
     * @type {string}
     * @memberof PdfInput
     */
    pdfUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PdfInput
     */
    pdfBase64?: string | null;
}

/**
 * Check if a given object implements the PdfInput interface.
 */
export function instanceOfPdfInput(value: object): value is PdfInput {
    return true;
}

export function PdfInputFromJSON(json: any): PdfInput {
    return PdfInputFromJSONTyped(json, false);
}

export function PdfInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PdfInput {
    if (json == null) {
        return json;
    }
    return {
        
        'pdfUrl': json['pdf_url'] == null ? undefined : json['pdf_url'],
        'pdfBase64': json['pdf_base64'] == null ? undefined : json['pdf_base64'],
    };
}

export function PdfInputToJSON(json: any): PdfInput {
    return PdfInputToJSONTyped(json, false);
}

export function PdfInputToJSONTyped(value?: PdfInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pdf_url': value['pdfUrl'],
        'pdf_base64': value['pdfBase64'],
    };
}

