/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PdfToolsResponse
 */
export interface PdfToolsResponse {
    /**
     * Signed URL to download the PDF
     * @type {string}
     * @memberof PdfToolsResponse
     */
    url: string;
    /**
     * Filename of the resulting PDF
     * @type {string}
     * @memberof PdfToolsResponse
     */
    filename: string;
    /**
     * Remaining credits after this request
     * @type {number}
     * @memberof PdfToolsResponse
     */
    creditsRemaining: number;
    /**
     * Seconds until the signed URL expires
     * @type {number}
     * @memberof PdfToolsResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the PdfToolsResponse interface.
 */
export function instanceOfPdfToolsResponse(value: object): value is PdfToolsResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('creditsRemaining' in value) || value['creditsRemaining'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function PdfToolsResponseFromJSON(json: any): PdfToolsResponse {
    return PdfToolsResponseFromJSONTyped(json, false);
}

export function PdfToolsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PdfToolsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'filename': json['filename'],
        'creditsRemaining': json['credits_remaining'],
        'expiresIn': json['expires_in'],
    };
}

export function PdfToolsResponseToJSON(json: any): PdfToolsResponse {
    return PdfToolsResponseToJSONTyped(json, false);
}

export function PdfToolsResponseToJSONTyped(value?: PdfToolsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'filename': value['filename'],
        'credits_remaining': value['creditsRemaining'],
        'expires_in': value['expiresIn'],
    };
}

