/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PDF variant for standards-compliant output (PDF/A).
 * @export
 */
export const PdfVariant = {
    PdfA1b: 'pdf/a-1b',
    PdfA2b: 'pdf/a-2b',
    PdfA3b: 'pdf/a-3b'
} as const;
export type PdfVariant = typeof PdfVariant[keyof typeof PdfVariant];


export function instanceOfPdfVariant(value: any): boolean {
    for (const key in PdfVariant) {
        if (Object.prototype.hasOwnProperty.call(PdfVariant, key)) {
            if (PdfVariant[key as keyof typeof PdfVariant] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PdfVariantFromJSON(json: any): PdfVariant {
    return PdfVariantFromJSONTyped(json, false);
}

export function PdfVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PdfVariant {
    return json as PdfVariant;
}

export function PdfVariantToJSON(value?: PdfVariant | null): any {
    return value as any;
}

export function PdfVariantToJSONTyped(value: any, ignoreDiscriminator: boolean): PdfVariant {
    return value as PdfVariant;
}

