/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRoutersV1PdfToolsExportType } from './AppRoutersV1PdfToolsExportType';
import {
    AppRoutersV1PdfToolsExportTypeFromJSON,
    AppRoutersV1PdfToolsExportTypeFromJSONTyped,
    AppRoutersV1PdfToolsExportTypeToJSON,
    AppRoutersV1PdfToolsExportTypeToJSONTyped,
} from './AppRoutersV1PdfToolsExportType';

/**
 * 
 * @export
 * @interface RotatePdfRequest
 */
export interface RotatePdfRequest {
    /**
     * `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
     * @type {AppRoutersV1PdfToolsExportType}
     * @memberof RotatePdfRequest
     */
    exportType?: AppRoutersV1PdfToolsExportType;
    /**
     * URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
     * @type {number}
     * @memberof RotatePdfRequest
     */
    expiration?: number;
    /**
     * 
     * @type {string}
     * @memberof RotatePdfRequest
     */
    filename?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RotatePdfRequest
     */
    pdfUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RotatePdfRequest
     */
    pdfBase64?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RotatePdfRequest
     */
    rotation?: number | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RotatePdfRequest
     */
    pageRotations?: { [key: string]: number; } | null;
}



/**
 * Check if a given object implements the RotatePdfRequest interface.
 */
export function instanceOfRotatePdfRequest(value: object): value is RotatePdfRequest {
    return true;
}

export function RotatePdfRequestFromJSON(json: any): RotatePdfRequest {
    return RotatePdfRequestFromJSONTyped(json, false);
}

export function RotatePdfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotatePdfRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exportType': json['export_type'] == null ? undefined : AppRoutersV1PdfToolsExportTypeFromJSON(json['export_type']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'pdfUrl': json['pdf_url'] == null ? undefined : json['pdf_url'],
        'pdfBase64': json['pdf_base64'] == null ? undefined : json['pdf_base64'],
        'rotation': json['rotation'] == null ? undefined : json['rotation'],
        'pageRotations': json['page_rotations'] == null ? undefined : json['page_rotations'],
    };
}

export function RotatePdfRequestToJSON(json: any): RotatePdfRequest {
    return RotatePdfRequestToJSONTyped(json, false);
}

export function RotatePdfRequestToJSONTyped(value?: RotatePdfRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'export_type': AppRoutersV1PdfToolsExportTypeToJSON(value['exportType']),
        'expiration': value['expiration'],
        'filename': value['filename'],
        'pdf_url': value['pdfUrl'],
        'pdf_base64': value['pdfBase64'],
        'rotation': value['rotation'],
        'page_rotations': value['pageRotations'],
    };
}

