/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for S3 configuration
 * @export
 * @interface S3ConfigRequest
 */
export interface S3ConfigRequest {
    /**
     * S3-compatible endpoint URL. Must start with https://
     * @type {string}
     * @memberof S3ConfigRequest
     */
    endpointUrl: string;
    /**
     * Access key ID for S3 authentication
     * @type {string}
     * @memberof S3ConfigRequest
     */
    accessKeyId: string;
    /**
     * 
     * @type {string}
     * @memberof S3ConfigRequest
     */
    secretAccessKey?: string | null;
    /**
     * S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)
     * @type {string}
     * @memberof S3ConfigRequest
     */
    bucketName: string;
    /**
     * Default path prefix for uploaded files. Can include slashes for folder structure
     * @type {string}
     * @memberof S3ConfigRequest
     */
    defaultPrefix?: string;
}

/**
 * Check if a given object implements the S3ConfigRequest interface.
 */
export function instanceOfS3ConfigRequest(value: object): value is S3ConfigRequest {
    if (!('endpointUrl' in value) || value['endpointUrl'] === undefined) return false;
    if (!('accessKeyId' in value) || value['accessKeyId'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    return true;
}

export function S3ConfigRequestFromJSON(json: any): S3ConfigRequest {
    return S3ConfigRequestFromJSONTyped(json, false);
}

export function S3ConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3ConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endpointUrl': json['endpoint_url'],
        'accessKeyId': json['access_key_id'],
        'secretAccessKey': json['secret_access_key'] == null ? undefined : json['secret_access_key'],
        'bucketName': json['bucket_name'],
        'defaultPrefix': json['default_prefix'] == null ? undefined : json['default_prefix'],
    };
}

export function S3ConfigRequestToJSON(json: any): S3ConfigRequest {
    return S3ConfigRequestToJSONTyped(json, false);
}

export function S3ConfigRequestToJSONTyped(value?: S3ConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint_url': value['endpointUrl'],
        'access_key_id': value['accessKeyId'],
        'secret_access_key': value['secretAccessKey'],
        'bucket_name': value['bucketName'],
        'default_prefix': value['defaultPrefix'],
    };
}

