/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for S3 configuration (with masked secret)
 * @export
 * @interface S3ConfigResponse
 */
export interface S3ConfigResponse {
    /**
     * Whether S3 is configured
     * @type {boolean}
     * @memberof S3ConfigResponse
     */
    configured: boolean;
    /**
     * S3-compatible endpoint URL
     * @type {string}
     * @memberof S3ConfigResponse
     */
    endpointUrl: string;
    /**
     * Access key ID
     * @type {string}
     * @memberof S3ConfigResponse
     */
    accessKeyId: string;
    /**
     * Masked secret access key (shows first 4 and last 4 characters)
     * @type {string}
     * @memberof S3ConfigResponse
     */
    secretAccessKeyMasked: string;
    /**
     * S3 bucket name
     * @type {string}
     * @memberof S3ConfigResponse
     */
    bucketName: string;
    /**
     * Default path prefix for uploads
     * @type {string}
     * @memberof S3ConfigResponse
     */
    defaultPrefix: string;
}

/**
 * Check if a given object implements the S3ConfigResponse interface.
 */
export function instanceOfS3ConfigResponse(value: object): value is S3ConfigResponse {
    if (!('configured' in value) || value['configured'] === undefined) return false;
    if (!('endpointUrl' in value) || value['endpointUrl'] === undefined) return false;
    if (!('accessKeyId' in value) || value['accessKeyId'] === undefined) return false;
    if (!('secretAccessKeyMasked' in value) || value['secretAccessKeyMasked'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('defaultPrefix' in value) || value['defaultPrefix'] === undefined) return false;
    return true;
}

export function S3ConfigResponseFromJSON(json: any): S3ConfigResponse {
    return S3ConfigResponseFromJSONTyped(json, false);
}

export function S3ConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3ConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'],
        'endpointUrl': json['endpoint_url'],
        'accessKeyId': json['access_key_id'],
        'secretAccessKeyMasked': json['secret_access_key_masked'],
        'bucketName': json['bucket_name'],
        'defaultPrefix': json['default_prefix'],
    };
}

export function S3ConfigResponseToJSON(json: any): S3ConfigResponse {
    return S3ConfigResponseToJSONTyped(json, false);
}

export function S3ConfigResponseToJSONTyped(value?: S3ConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'endpoint_url': value['endpointUrl'],
        'access_key_id': value['accessKeyId'],
        'secret_access_key_masked': value['secretAccessKeyMasked'],
        'bucket_name': value['bucketName'],
        'default_prefix': value['defaultPrefix'],
    };
}

