/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generic success response for S3 operations
 * @export
 * @interface S3SuccessResponse
 */
export interface S3SuccessResponse {
    /**
     * Whether the operation succeeded
     * @type {boolean}
     * @memberof S3SuccessResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the S3SuccessResponse interface.
 */
export function instanceOfS3SuccessResponse(value: object): value is S3SuccessResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function S3SuccessResponseFromJSON(json: any): S3SuccessResponse {
    return S3SuccessResponseFromJSONTyped(json, false);
}

export function S3SuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3SuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function S3SuccessResponseToJSON(json: any): S3SuccessResponse {
    return S3SuccessResponseToJSONTyped(json, false);
}

export function S3SuccessResponseToJSONTyped(value?: S3SuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

