/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for S3 connection test
 * @export
 * @interface S3TestResponse
 */
export interface S3TestResponse {
    /**
     * Whether the connection test succeeded
     * @type {boolean}
     * @memberof S3TestResponse
     */
    success: boolean;
    /**
     * Test result message
     * @type {string}
     * @memberof S3TestResponse
     */
    message: string;
}

/**
 * Check if a given object implements the S3TestResponse interface.
 */
export function instanceOfS3TestResponse(value: object): value is S3TestResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function S3TestResponseFromJSON(json: any): S3TestResponse {
    return S3TestResponseFromJSONTyped(json, false);
}

export function S3TestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3TestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function S3TestResponseToJSON(json: any): S3TestResponse {
    return S3TestResponseToJSONTyped(json, false);
}

export function S3TestResponseToJSONTyped(value?: S3TestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

