/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to set the default version
 * @export
 * @interface SetDefaultVersionRequest
 */
export interface SetDefaultVersionRequest {
    /**
     * Version number to set as default
     * @type {number}
     * @memberof SetDefaultVersionRequest
     */
    versionNumber: number;
}

/**
 * Check if a given object implements the SetDefaultVersionRequest interface.
 */
export function instanceOfSetDefaultVersionRequest(value: object): value is SetDefaultVersionRequest {
    if (!('versionNumber' in value) || value['versionNumber'] === undefined) return false;
    return true;
}

export function SetDefaultVersionRequestFromJSON(json: any): SetDefaultVersionRequest {
    return SetDefaultVersionRequestFromJSONTyped(json, false);
}

export function SetDefaultVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetDefaultVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'versionNumber': json['version_number'],
    };
}

export function SetDefaultVersionRequestToJSON(json: any): SetDefaultVersionRequest {
    return SetDefaultVersionRequestToJSONTyped(json, false);
}

export function SetDefaultVersionRequestToJSONTyped(value?: SetDefaultVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version_number': value['versionNumber'],
    };
}

