/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateListItem } from './TemplateListItem';
import {
    TemplateListItemFromJSON,
    TemplateListItemFromJSONTyped,
    TemplateListItemToJSON,
    TemplateListItemToJSONTyped,
} from './TemplateListItem';

/**
 * Response for template list endpoint
 * @export
 * @interface TemplatesListResponse
 */
export interface TemplatesListResponse {
    /**
     * 
     * @type {Array<TemplateListItem>}
     * @memberof TemplatesListResponse
     */
    templates: Array<TemplateListItem>;
}

/**
 * Check if a given object implements the TemplatesListResponse interface.
 */
export function instanceOfTemplatesListResponse(value: object): value is TemplatesListResponse {
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function TemplatesListResponseFromJSON(json: any): TemplatesListResponse {
    return TemplatesListResponseFromJSONTyped(json, false);
}

export function TemplatesListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': ((json['templates'] as Array<any>).map(TemplateListItemFromJSON)),
    };
}

export function TemplatesListResponseToJSON(json: any): TemplatesListResponse {
    return TemplatesListResponseToJSONTyped(json, false);
}

export function TemplatesListResponseToJSONTyped(value?: TemplatesListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': ((value['templates'] as Array<any>).map(TemplateListItemToJSON)),
    };
}

