/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Spec for array item fields
 * @export
 * @interface TemplateFieldSpec
 */
export interface TemplateFieldSpec {
    /**
     * Field name
     * @type {string}
     * @memberof TemplateFieldSpec
     */
    name: string;
    /**
     * Field label
     * @type {string}
     * @memberof TemplateFieldSpec
     */
    label: string;
    /**
     * Field type: text, number
     * @type {string}
     * @memberof TemplateFieldSpec
     */
    type?: string;
}

/**
 * Check if a given object implements the TemplateFieldSpec interface.
 */
export function instanceOfTemplateFieldSpec(value: object): value is TemplateFieldSpec {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function TemplateFieldSpecFromJSON(json: any): TemplateFieldSpec {
    return TemplateFieldSpecFromJSONTyped(json, false);
}

export function TemplateFieldSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateFieldSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'label': json['label'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TemplateFieldSpecToJSON(json: any): TemplateFieldSpec {
    return TemplateFieldSpecToJSONTyped(json, false);
}

export function TemplateFieldSpecToJSONTyped(value?: TemplateFieldSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'label': value['label'],
        'type': value['type'],
    };
}

