/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Template item in list response
 * @export
 * @interface TemplateListItem
 */
export interface TemplateListItem {
    /**
     * Template short ID (12 characters)
     * @type {string}
     * @memberof TemplateListItem
     */
    id: string;
    /**
     * Template name
     * @type {string}
     * @memberof TemplateListItem
     */
    name: string;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof TemplateListItem
     */
    createdAt: string;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof TemplateListItem
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the TemplateListItem interface.
 */
export function instanceOfTemplateListItem(value: object): value is TemplateListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TemplateListItemFromJSON(json: any): TemplateListItem {
    return TemplateListItemFromJSONTyped(json, false);
}

export function TemplateListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function TemplateListItemToJSON(json: any): TemplateListItem {
    return TemplateListItemToJSONTyped(json, false);
}

export function TemplateListItemToJSONTyped(value?: TemplateListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

