/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Transaction record
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * Unique transaction reference (UUID)
     * @type {string}
     * @memberof Transaction
     */
    transactionRef: string;
    /**
     * Transaction type: PDFGEN, PURCHASE, REFUND, BONUS
     * @type {string}
     * @memberof Transaction
     */
    transactionType: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    templateId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    execTm?: number | null;
    /**
     * Credits consumed (positive) or added (negative)
     * @type {number}
     * @memberof Transaction
     */
    credits: number;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof Transaction
     */
    createdAt: string;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    if (!('transactionRef' in value) || value['transactionRef'] === undefined) return false;
    if (!('transactionType' in value) || value['transactionType'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionRef': json['transaction_ref'],
        'transactionType': json['transaction_type'],
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'execTm': json['exec_tm'] == null ? undefined : json['exec_tm'],
        'credits': json['credits'],
        'createdAt': json['created_at'],
    };
}

export function TransactionToJSON(json: any): Transaction {
    return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_ref': value['transactionRef'],
        'transaction_type': value['transactionType'],
        'template_id': value['templateId'],
        'exec_tm': value['execTm'],
        'credits': value['credits'],
        'created_at': value['createdAt'],
    };
}

