/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to update a version's tag or description. Send null to clear a field.
 * @export
 * @interface UpdateVersionRequest
 */
export interface UpdateVersionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateVersionRequest
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateVersionRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the UpdateVersionRequest interface.
 */
export function instanceOfUpdateVersionRequest(value: object): value is UpdateVersionRequest {
    return true;
}

export function UpdateVersionRequestFromJSON(json: any): UpdateVersionRequest {
    return UpdateVersionRequestFromJSONTyped(json, false);
}

export function UpdateVersionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVersionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateVersionRequestToJSON(json: any): UpdateVersionRequest {
    return UpdateVersionRequestToJSONTyped(json, false);
}

export function UpdateVersionRequestToJSONTyped(value?: UpdateVersionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'description': value['description'],
    };
}

