/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Version item in list response
 * @export
 * @interface VersionItem
 */
export interface VersionItem {
    /**
     * Version number
     * @type {number}
     * @memberof VersionItem
     */
    versionNumber: number;
    /**
     * 
     * @type {string}
     * @memberof VersionItem
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VersionItem
     */
    description?: string | null;
    /**
     * Whether this is the default version used by the API
     * @type {boolean}
     * @memberof VersionItem
     */
    isDefault?: boolean;
    /**
     * ISO 8601 timestamp
     * @type {string}
     * @memberof VersionItem
     */
    createdAt: string;
}

/**
 * Check if a given object implements the VersionItem interface.
 */
export function instanceOfVersionItem(value: object): value is VersionItem {
    if (!('versionNumber' in value) || value['versionNumber'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function VersionItemFromJSON(json: any): VersionItem {
    return VersionItemFromJSONTyped(json, false);
}

export function VersionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionItem {
    if (json == null) {
        return json;
    }
    return {
        
        'versionNumber': json['version_number'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'description': json['description'] == null ? undefined : json['description'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'createdAt': json['created_at'],
    };
}

export function VersionItemToJSON(json: any): VersionItem {
    return VersionItemToJSONTyped(json, false);
}

export function VersionItemToJSONTyped(value?: VersionItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version_number': value['versionNumber'],
        'tag': value['tag'],
        'description': value['description'],
        'is_default': value['isDefault'],
        'created_at': value['createdAt'],
    };
}

