/* tslint:disable */
/* eslint-disable */
/**
 * TemplateFox API
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionItem } from './VersionItem';
import {
    VersionItemFromJSON,
    VersionItemFromJSONTyped,
    VersionItemToJSON,
    VersionItemToJSONTyped,
} from './VersionItem';

/**
 * Response for versions list
 * @export
 * @interface VersionsListResponse
 */
export interface VersionsListResponse {
    /**
     * 
     * @type {Array<VersionItem>}
     * @memberof VersionsListResponse
     */
    versions: Array<VersionItem>;
}

/**
 * Check if a given object implements the VersionsListResponse interface.
 */
export function instanceOfVersionsListResponse(value: object): value is VersionsListResponse {
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function VersionsListResponseFromJSON(json: any): VersionsListResponse {
    return VersionsListResponseFromJSONTyped(json, false);
}

export function VersionsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'versions': ((json['versions'] as Array<any>).map(VersionItemFromJSON)),
    };
}

export function VersionsListResponseToJSON(json: any): VersionsListResponse {
    return VersionsListResponseToJSONTyped(json, false);
}

export function VersionsListResponseToJSONTyped(value?: VersionsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versions': ((value['versions'] as Array<any>).map(VersionItemToJSON)),
    };
}

